### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by makovka44** [lin-cadez/lin-cadez.github.io#3]
Ko klikneš za embed, se ti odpre okno in ne morš več zapret. Pa še cerkve v Šmartnem pri Litiji še kar ni.

**Comment by lin-cadez** [comment]
A zdej je?

**Comment by lin-cadez** [comment]
![image](https://user-images.githubusercontent.com/68005465/229800233-fdd12321-ba4e-47cd-a3aa-d9a7b66b0a7f.png)
Evo zdej bi pa mogla bit.
